logging:
#  level: 
#    com.taba.springboot.profile.controller: ERROR           
  file: logs/prod.log
  
server:
  port: 8443

  ssl:
    key-store: classpath:mykeystore.jks
    key-store-password: changeit
    key-password: changeit
  
 
